timeout: 600s
availableSecrets:
  secretManager:
  - versionName: projects/1029845047729/secrets/SLACK_HOOK_URL/versions/1
    env: 'SLACK_HOOK_URL'
substitutions:
  _BASE_TAG: 2.0.0
options:
  automapSubstitutions: true
steps:
- name: gcr.io/kaniko-project/executor:latest
  args: [ "--dockerfile=dockerfiles/base/cypress/Dockerfile",
          "--destination=us-docker.pkg.dev/cykubed/public/cypress-base:${_BASE_TAG}",
          "--cache=true"]

#- name: gcr.io/kaniko-project/executor:latest
#  args: [ "--dockerfile=dockerfiles/base/node/Dockerfile",
#          "--destination=us-docker.pkg.dev/cykubed/public/cypress-node-16:${_BASE_TAG}",
#          "--build-arg=node=16",
#          "--build-arg=basetag=cypress-base:${_BASE_TAG}",
#          "--cache=true"]
#
#- name: gcr.io/kaniko-project/executor:latest
#  args: [ "--dockerfile=dockerfiles/base/node/Dockerfile",
#          "--destination=us-docker.pkg.dev/cykubed/public/cypress-node-18:${_BASE_TAG}",
#          "--build-arg=node=18",
#          "--build-arg=basetag=cypress-base:${_BASE_TAG}",
#          "--cache=true"]

- name: gcr.io/kaniko-project/executor:latest
  args: [ "--dockerfile=dockerfiles/base/node/Dockerfile",
          "--destination=us-docker.pkg.dev/cykubed/public/cypress-node-20:${_BASE_TAG}",
          "--build-arg=node=20",
          "--build-arg=basetag=cypress-base:${_BASE_TAG}",
          "--cache=true"]

- name: alpine/httpie
  id: Notify Slack
  secretEnv: ['SLACK_HOOK_URL']
  script: |
    echo "{\"text\":\"Cykubed runner *base* images created with tag ${_BASE_TAG}\"}" > payload.json
    http POST $SLACK_HOOK_URL < payload.json
