timeout: 600s
availableSecrets:
  secretManager:
  - versionName: projects/1029845047729/secrets/SLACK_HOOK_URL/versions/1
    env: 'SLACK_HOOK_URL'
substitutions:
  _BASE_TAG: 2.0.0
  _TAG: 3.0.0
  _REGION: us
options:
  automapSubstitutions: true
steps:

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_REGION}-docker.pkg.dev/cykubed/public/runner/app-base:latest',
                   '-t', '${_REGION}-docker.pkg.dev/cykubed/public/runner/app-base:${_TAG}',
          '-f', 'dockerfiles/full/app/Dockerfile',
          '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '-a', '${_REGION}-docker.pkg.dev/cykubed/public/runner/app-main' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t', '${_REGION}-docker.pkg.dev/cykubed/public/runner/cypress-node-20:latest',
          '-t', '${_REGION}-docker.pkg.dev/cykubed/public/runner/cypress-node-20:${_TAG}',
          '--build-arg', 'base=cypress-base-node-20:${_BASE_TAG}',
          '--build-arg', 'tag=${_TAG}',
          '-f', 'dockerfiles/full/runner/Dockerfile',
          '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '-a', '${_REGION}-docker.pkg.dev/cykubed/public/runner/cypress-node-20' ]

- name: alpine/httpie
  id: Notify Slack
  secretEnv: ['SLACK_HOOK_URL']
  script: |
    echo "{\"text\":\"Cykubed *full* runner images created with tag ${_TAG}\"}" > payload.json
    http POST $SLACK_HOOK_URL < payload.json
