timeout: 3000s
availableSecrets:
  secretManager:
  - versionName: projects/1029845047729/secrets/SLACK_HOOK_URL/versions/1
    env: 'SLACK_HOOK_URL'
  - versionName: projects/1029845047729/secrets/CYKUBED_API_TOKEN/versions/1
    env: 'CYKUBED_API_TOKEN'
substitutions:
  _BASE_TAG: 2.0.0
  _TAG: 4.0.0
  _REGION: us
  _API_URL: https://api.cykubed.com
options:
  automapSubstitutions: true
steps:
- name: 'gcr.io/cloud-builders/git'
  script: |
    git config -f .gitmodules submodule.src/cykubedrunner/common.url https://github.com/cykubed/cykubed-common.git
    git submodule init
    git submodule update

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t', '${_REGION}-docker.pkg.dev/cykubed/public/runner/playwright-node-20:latest',
          '-t', '${_REGION}-docker.pkg.dev/cykubed/public/runner/playwright-node-20:${_TAG}',
          '--build-arg', 'base=playwright-base-node-20:${_BASE_TAG}',
          '--build-arg', 'tag=${_TAG}',
          '-f', 'dockerfiles/full/Dockerfile',
          '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '-a', '${_REGION}-docker.pkg.dev/cykubed/public/runner/playwright-node-20' ]



- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t', '${_REGION}-docker.pkg.dev/cykubed/public/runner/cypress-node-16:latest',
          '-t', '${_REGION}-docker.pkg.dev/cykubed/public/runner/cypress-node-16:${_TAG}',
          '--build-arg', 'base=cypress-base-node-16:${_BASE_TAG}',
          '--build-arg', 'tag=${_TAG}',
          '-f', 'dockerfiles/full/Dockerfile',
          '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '-a', '${_REGION}-docker.pkg.dev/cykubed/public/runner/cypress-node-16' ]


- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t', '${_REGION}-docker.pkg.dev/cykubed/public/runner/cypress-node-18:latest',
          '-t', '${_REGION}-docker.pkg.dev/cykubed/public/runner/cypress-node-18:${_TAG}',
          '--build-arg', 'base=cypress-base-node-18:${_BASE_TAG}',
          '--build-arg', 'tag=${_TAG}',
          '-f', 'dockerfiles/full/Dockerfile',
          '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '-a', '${_REGION}-docker.pkg.dev/cykubed/public/runner/cypress-node-18' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t', '${_REGION}-docker.pkg.dev/cykubed/public/runner/cypress-node-20:latest',
          '-t', '${_REGION}-docker.pkg.dev/cykubed/public/runner/cypress-node-20:${_TAG}',
          '--build-arg', 'base=cypress-base-node-20:${_BASE_TAG}',
          '--build-arg', 'tag=${_TAG}',
          '-f', 'dockerfiles/full/Dockerfile',
          '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '-a', '${_REGION}-docker.pkg.dev/cykubed/public/runner/cypress-node-20' ]


- name: alpine/httpie
  id: Set current version number
  script: |
     http POST "${_API_URL}/admin/image/runner/current-version/${_TAG}" -A bearer -a $CYKUBED_API_TOKEN
  secretEnv: ['CYKUBED_API_TOKEN']

- name: alpine/httpie
  id: Notify Slack
  secretEnv: ['SLACK_HOOK_URL']
  script: |
    echo "{\"text\":\"Cykubed *full* runner images created with tag ${_TAG}\"}" > payload.json
    http POST $SLACK_HOOK_URL < payload.json
