 steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t $$USERNAME/cykube-runner:$COMMIT_SHA .']
   secretEnv: ['USERNAME']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push $$USERNAME/cykube-runner:$COMMIT_SHA']
   secretEnv: ['USERNAME']
 availableSecrets:
   secretManager:
   - versionName: projects/1090211518452/secrets/docker-username/versions/1
     env: 'USERNAME'
   - versionName: projects/1090211518452/secrets/docker-password/versions/1
     env: 'PASSWORD'
