timeout: 900s
steps:
  - name: 'gcr.io/cloud-builders/git'
    script: |
      git config -f .gitmodules submodule.src/common.url https://source.developers.google.com/p/cykubeapp/r/github_cykube_cykube-common
      git submodule init
      git submodule update

  - name: alpine/httpie
    id: Get next version number
    entrypoint: sh
    args:
      - '-c'
      - |-
        http GET https://api.cykube.net/admin/image/runner/next-version/minor -A bearer -a $$CYKUBE_API_TOKEN -b > /workspace/version.txt && echo "Building version $(cat /workspace/version.txt)"
    secretEnv: ['CYKUBE_API_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ './scripts/cloudbuild/build-docker.sh', $(cat /workspace/version.txt) ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ './scripts/cloudbuild/push-docker.sh', $(cat /workspace/version.txt) ]

  - name: alpine/httpie
    id: Update Cykube app with latest runner images and notify Slack
    entrypoint: sh
    args:
      - '-c'
      - |-
       http -A bearer -a $$CYKUBE_API_TOKEN POST https://api.cykube.net/admin/runner/image < /workspace/cykube-payload.json &&
       http POST https://hooks.slack.com/services/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 < /workspace/slack-payload.json &&
       http POST "https://api.cykube.net/admin/image/runner/current-version/$(cat /workspace/version.txt)" -A bearer -a $$CYKUBE_API_TOKEN
    secretEnv: ['CYKUBE_API_TOKEN']

availableSecrets:
  secretManager:
    - versionName: projects/489847359241/secrets/cykube-api-token/versions/1
      env: 'CYKUBE_API_TOKEN'
