[tool.poetry]
name = "cykuberunner"
version = "0.1.0"
description = ""
authors = ["nick <nickbrook72@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.1"
pydantic = "^1.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
