[tool.poetry]
name = "cykuberunner"
version = "0.1.0"
description = ""
authors = ["nick <nickbrook72@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.2"
httpx = "^0.23.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
respx = "^0.20.1"
pytest-asyncio = "^0.20.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
