#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: build-pvc
#  namespace: cykubed
#spec:
#  storageClassName: "cykubed-storageclass"
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: node-pvc
#  namespace: cykubed
#spec:
#  storageClassName: "cykubed-storageclass"
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#---
apiVersion: v1
kind: Pod
metadata:
  name: build-pod
  namespace: cykubed
spec:
  serviceAccountName: "cykubed"
  restartPolicy: Never
  volumes:
    - name: build-volume
      persistentVolumeClaim:
        claimName: build-pvc
    - name: node-volume
      persistentVolumeClaim:
        claimName: node-pvc
  securityContext:
    runAsNonRoot: true
    fsGroup: 10000
    runAsUser: 10000
    runAsGroup: 10000
  containers:
    - name: shell
      image: europe-docker.pkg.dev/cykubeapp/cykubed/runner-node16.x:1.3.0
      volumeMounts:
      - mountPath: "/build"
        name: build-volume
      - mountPath: "/node"
        name: node-volume
      command: ["/bin/sleep", "3600"]
      resources:
        requests:
          cpu: "1"
          memory: 2Gi


