apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-pvc
  namespace: cykubed
spec:
  storageClassName: "cykubed-storageclass"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: build-pod
  namespace: cykubed
spec:
  serviceAccountName: "cykubed"
  restartPolicy: Never
  nodeSelector:
    cloud.google.com/gke-spot: "true"
  volumes:
    - name: build-volume
      persistentVolumeClaim:
        claimName: build-pvc
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
  securityContext:
    runAsNonRoot: true
    fsGroup: 10000
    runAsUser: 10000
    runAsGroup: 10000
  containers:
    - name: shell
      image: europe-docker.pkg.dev/cykubeapp/cykubed/runner-node16.x:latest
      command: ["/bin/sleep", "3600"]
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
        - mountPath: "/build"
          name: build-volume


