apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: cykubed
spec:
  storageClassName: "cykubed-storageclass"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
