apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-ro-1
  namespace: cykubed
spec:
  storageClassName: "premium-rwo"
  accessModes:
    - ReadOnlyMany
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: build-1
  resources:
    requests:
      storage: 10Gi
