apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-1
  namespace: cykubed
spec:
  storageClassName: "cykubed-storageclass"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: runshell
  namespace: cykubed
spec:
  volumes:
    - name: build-volume
      persistentVolumeClaim:
        claimName: "build-1"
    - name: node-volume
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "premium-rwo"
            dataSource:
              apiGroup: snapshot.storage.k8s.io
              kind: VolumeSnapshot
              name: build-1
            resources:
              requests:
                storage: "10Gi"
  securityContext:
    runAsNonRoot: true
    fsGroup: 10000
    runAsUser: 10000
    runAsGroup: 10000
  containers:
    - name: shell
      image: europe-west2-docker.pkg.dev/cykubeapp/cykube/runner-node16.x:1.2.0
      volumeMounts:
      - mountPath: "/node"
        name: node-volume
      - mountPath: "/build"
        name: build-volume
      command: ["/bin/sleep", "3600"]
      imagePullPolicy: Always
      resources:
        requests:
          cpu: 1
          memory: '500M'
