apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: build-2
  namespace: cykubed
spec:
  volumeSnapshotClassName: cykubed-snapshotclass
  source:
    persistentVolumeClaimName: build-pvc

