apiVersion: v1
kind: Pod
metadata:
  name: runshell
  namespace: cykube
spec:
  containers:
    - name: shell
      image: nickbrookck/cykube-runner:node16.x-1f6a46c
      command: ["/bin/sleep", "3600"]
      resources:
        requests:
          cpu: 4
          memory: '2G'
          ephemeral-storage: "4Gi"
        limits:
          cpu: 4
          memory: '4G'
          ephemeral-storage: "4Gi"
      env:
      - name: MONGO_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "cykube-mongodb"
            key: "mongodb-root-password"
      envFrom:
        - configMapRef:
            name: cykube-agent-configmap
        - secretRef:
            name: cykube-agent-secrets

