apiVersion: v1
kind: Pod
metadata:
  name: runshell
  namespace: cykube
spec:
  serviceAccountName: "cykube"
  volumes:
    - name: scratch-volume
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "premium-rwo"
            resources:
              requests:
                storage: "4Gi"
  containers:
    - name: shell
      image: europe-west2-docker.pkg.dev/cykubeapp/cykube/runner-node16.x:1.1.0
      volumeMounts:
      - mountPath: "/build"
        name: scratch-volume
      command: ["/bin/sleep", "3600"]
      resources:
        requests:
          cpu: 1
          memory: '200M'
      envFrom:
        - configMapRef:
            name: cykube-agent-configmap
        - secretRef:
            name: cykube-agent-secrets
      env:
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "cykube-redis"
            key: "redis-password"
