timeout: 900s
availableSecrets:
  secretManager:
  - versionName: projects/cykubed/secrets/SLACK_HOOK_URL/versions/1
    env: 'SLACK_HOOK_URL'
  - versionName: projects/cykubed/secrets/cykubed-api-token/versions/1
    env: 'CYKUBED_API_TOKEN'
steps:

- name: gcr.io/kaniko-project/executor:latest
  args: [ "--dockerfile=dockerfiles/generated/full/node-14/Dockerfile",
          "--destination=us-docker.pkg.dev/cykubed/public/node-14:3.8.0",
          "--cache=true"]
- name: gcr.io/kaniko-project/executor:latest
  args: [ "--dockerfile=dockerfiles/generated/full/node-14-chrome/Dockerfile",
          "--destination=us-docker.pkg.dev/cykubed/public/node-14-chrome:3.8.0",
          "--cache=true"]
- name: gcr.io/kaniko-project/executor:latest
  args: [ "--dockerfile=dockerfiles/generated/full/node-14-edge/Dockerfile",
          "--destination=us-docker.pkg.dev/cykubed/public/node-14-edge:3.8.0",
          "--cache=true"]
- name: gcr.io/kaniko-project/executor:latest
  args: [ "--dockerfile=dockerfiles/generated/full/node-14-chrome-edge-firefox/Dockerfile",
          "--destination=us-docker.pkg.dev/cykubed/public/node-14-chrome-edge-firefox:3.8.0",
          "--cache=true"]

- name: alpine/httpie
  id: Update Cykubed app with latest runner images and notify Slack
  secretEnv: ['SLACK_HOOK_URL', 'CYKUBED_API_TOKEN']
  script: |
    http POST https://api.cykubed.com/admin/runner/image -A bearer -a $CYKUBED_API_TOKEN  < dockerfiles/generated/full/cykubed-payload.json
    http POST $SLACK_HOOK_URL < dockerfiles/generated/full/slack-payload.json
